#!/bin/bash
# Build ShutterSense Agent for Windows
# Must be run on a Windows system or via cross-compilation tools
# Produces a standalone .exe that runs without Python installed
#
# Output structure: dist/{version}/shuttersense-agent-windows-amd64.exe

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$AGENT_DIR")"
BUILD_DIR="$AGENT_DIR/dist"

echo "Building ShutterSense Agent for Windows..."

# Verify Python version (3.11+ required — bundled into the binary by PyInstaller)
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')")
if ! python3 -c "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)"; then
    echo "Error: Python 3.11+ required for build, found $PYTHON_VERSION"
    echo "The build Python is bundled into the binary and must match project requirements."
    exit 1
fi
echo "Python: $PYTHON_VERSION"

# Ensure we're in the agent directory
cd "$AGENT_DIR"

# Windows platform (only amd64 supported currently)
PLATFORM="windows-amd64"

# Get version from environment or Git
if [ -n "$SHUSAI_VERSION" ]; then
    VERSION="$SHUSAI_VERSION"
else
    # Get version from Git using the same logic as version.py
    VERSION=$(git describe --tags --long --always 2>/dev/null || echo "")
    if [ -n "$VERSION" ]; then
        # Parse: v1.2.3-0-ga1b2c3d (on tag) or v1.2.3-5-ga1b2c3d (5 commits after)
        if [[ "$VERSION" =~ ^(.+)-([0-9]+)-g([a-f0-9]+)$ ]]; then
            TAG="${BASH_REMATCH[1]}"
            COMMITS="${BASH_REMATCH[2]}"
            HASH="${BASH_REMATCH[3]}"
            if [ "$COMMITS" = "0" ]; then
                VERSION="$TAG"
            else
                VERSION="${TAG}-dev.${COMMITS}+${HASH}"
            fi
        else
            # Just a commit hash (no tags)
            HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
            VERSION="v0.0.0-dev+$HASH"
        fi
    else
        VERSION="v0.0.0-dev+unknown"
    fi
fi

echo "Version: $VERSION"
echo "Platform: $PLATFORM"

# Write version to _version.py so it gets bundled into the binary
# This ensures the built binary reports the correct version
cat > "$AGENT_DIR/src/_version.py" << EOF
# Auto-generated by build script - DO NOT EDIT
__version__ = "$VERSION"
EOF
echo "Wrote version to src/_version.py"

# Set up output paths
OUTPUT_DIR="$BUILD_DIR/$VERSION"
BINARY_NAME="shuttersense-agent-$PLATFORM"

# Clean previous spec file to avoid stale path issues
# The spec file stores relative paths that break on subsequent runs
rm -rf "$BUILD_DIR/spec"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Install build dependencies if needed
pip install -q "pyinstaller==6.18.0"

# Build the agent binary
pyinstaller \
    --name "$BINARY_NAME" \
    --onefile \
    --console \
    --clean \
    --noconfirm \
    --distpath "$OUTPUT_DIR" \
    --workpath "$BUILD_DIR/build" \
    --specpath "$BUILD_DIR/spec" \
    --add-data "$AGENT_DIR/src;src" \
    --add-data "$AGENT_DIR/cli;cli" \
    --add-data "$PROJECT_ROOT/utils;utils" \
    --hidden-import "websockets" \
    --hidden-import "httpx" \
    --hidden-import "pydantic" \
    --hidden-import "cryptography" \
    --hidden-import "click" \
    --hidden-import "yaml" \
    cli/main.py

# Calculate checksum for attestation
BINARY_PATH="$OUTPUT_DIR/$BINARY_NAME.exe"
if [ -f "$BINARY_PATH" ]; then
    CHECKSUM=$(sha256sum "$BINARY_PATH" | cut -d' ' -f1)
    echo "$CHECKSUM" > "$BINARY_PATH.sha256"
    echo "Build complete: $BINARY_PATH"
    echo "SHA-256: $CHECKSUM"
else
    echo "Error: Binary not found at $BINARY_PATH"
    exit 1
fi
