"""
Register CLI command.

Handles agent registration with the ShutterSense server.

Issue #90 - Distributed Agent Architecture (Phase 3)
Task: T042
"""

import asyncio
import platform
import socket
from typing import Optional

import click

from src import __version__
from src.config import AgentConfig
from src.capabilities import detect_capabilities
from src.attestation import get_attestation_info
from src.api_client import (
    AgentApiClient,
    ConnectionError as AgentConnectionError,
    RegistrationError,
)


# ============================================================================
# Helper Functions
# ============================================================================


def get_system_info() -> tuple[str, str]:
    """
    Get system hostname and OS information.

    Returns:
        Tuple of (hostname, os_info)
    """
    hostname = socket.gethostname()

    # Build OS info string
    system = platform.system()
    release = platform.release()
    machine = platform.machine()

    if system == "Darwin":
        # macOS: Try to get version name
        try:
            import subprocess

            version = subprocess.check_output(
                ["sw_vers", "-productVersion"], text=True
            ).strip()
            os_info = f"macOS {version} ({machine})"
        except Exception:
            os_info = f"macOS {release} ({machine})"
    elif system == "Windows":
        os_info = f"Windows {platform.win32_ver()[0]} ({machine})"
    else:
        # Linux or other
        os_info = f"{system} {release} ({machine})"

    return hostname, os_info


# ============================================================================
# Register Command
# ============================================================================


@click.command()
@click.option(
    "--server",
    "-s",
    required=True,
    help="ShutterSense server URL (e.g., http://localhost:8000)",
)
@click.option(
    "--token",
    "-t",
    required=True,
    help="One-time registration token from server admin",
)
@click.option(
    "--name",
    "-n",
    default=None,
    help="Agent display name (defaults to hostname)",
)
@click.option(
    "--force",
    "-f",
    is_flag=True,
    default=False,
    help="Force re-registration if already registered",
)
@click.pass_context
def register(
    ctx: click.Context,
    server: str,
    token: str,
    name: Optional[str],
    force: bool,
) -> None:
    """
    Register this agent with a ShutterSense server.

    Requires a one-time registration token generated by a server administrator.
    After successful registration, the agent can be started with 'start' command.

    Example:

        shuttersense-agent register --server http://localhost:8000 --token art_xxxxx
    """
    # Load existing config
    config = AgentConfig()

    # Check if already registered
    if config.is_registered and not force:
        click.echo(
            click.style("Error: ", fg="red", bold=True)
            + f"Agent is already registered as {config.agent_guid}"
        )
        click.echo(
            "Use --force to re-register (this will replace the existing registration)"
        )
        ctx.exit(1)

    # Get system information
    hostname, os_info = get_system_info()

    # Use hostname as default name if not provided
    if not name:
        name = hostname

    # Detect capabilities
    capabilities = detect_capabilities()

    # Get authorized roots from config (if any)
    authorized_roots = config.authorized_roots

    # Get attestation info (checksum and platform) from the attestation module
    attestation = get_attestation_info()
    binary_checksum = attestation.get('checksum')
    agent_platform = attestation.get('platform')

    click.echo(f"Registering agent '{name}' with server {server}...")
    click.echo(f"  Hostname: {hostname}")
    click.echo(f"  OS: {os_info}")
    click.echo(f"  Capabilities: {', '.join(capabilities)}")
    if binary_checksum:
        click.echo(f"  Binary checksum: {binary_checksum[:16]}...")
    if agent_platform:
        click.echo(f"  Platform: {agent_platform}")
    if authorized_roots:
        click.echo(f"  Authorized roots: {', '.join(authorized_roots)}")

    # Perform registration
    try:
        result = asyncio.run(_register_async(
            server, token, name, hostname, os_info,
            capabilities, authorized_roots, binary_checksum, agent_platform,
        ))
    except AgentConnectionError as e:
        click.echo(click.style("Error: ", fg="red", bold=True) + f"Connection failed: {e}")
        ctx.exit(1)
    except RegistrationError as e:
        click.echo(click.style("Error: ", fg="red", bold=True) + f"Registration failed: {e}")
        ctx.exit(1)
    except Exception as e:
        click.echo(click.style("Error: ", fg="red", bold=True) + f"Unexpected error: {e}")
        ctx.exit(1)

    # Update config with registration info
    config.server_url = server
    config.update_registration(
        agent_guid=result["guid"],
        api_key=result["api_key"],
        agent_name=result["name"],
    )

    # Success message
    click.echo()
    click.echo(click.style("Registration successful!", fg="green", bold=True))
    click.echo(f"  Agent GUID: {result['guid']}")
    click.echo(f"  Team GUID: {result['team_guid']}")
    click.echo(f"  Config saved to: {config.config_path}")
    click.echo()
    click.echo("To start the agent, run:")
    click.echo(click.style("  shuttersense-agent start", fg="cyan"))


async def _register_async(
    server: str,
    token: str,
    name: str,
    hostname: str,
    os_info: str,
    capabilities: list[str],
    authorized_roots: list[str],
    binary_checksum: Optional[str] = None,
    agent_platform: Optional[str] = None,
) -> dict:
    """
    Async registration helper.

    Args:
        server: Server URL
        token: Registration token
        name: Agent name
        hostname: Machine hostname
        os_info: OS information
        capabilities: Agent capabilities
        authorized_roots: Authorized local filesystem roots
        binary_checksum: SHA-256 of agent binary (packaged builds only)
        agent_platform: Platform identifier (e.g., 'darwin-arm64')

    Returns:
        Registration response
    """
    async with AgentApiClient(server_url=server) as client:
        return await client.register(
            registration_token=token,
            name=name,
            hostname=hostname,
            os_info=os_info,
            capabilities=capabilities,
            authorized_roots=authorized_roots,
            version=__version__,
            binary_checksum=binary_checksum,
            platform=agent_platform,
        )
