"""Insert release manifest for v1.20 (darwin-arm64).

Revision ID: 074_release_1_20_darwin_arm64
Revises: 073_agent_is_verified
Create Date: 2026-02-20

Auto-generated by build script after successful agent binary build.
Issue #241: Build scripts auto-generate Alembic migration for manifests.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '074_release_1_20_darwin_arm64'
down_revision = '073_agent_is_verified'
branch_labels = None
depends_on = None

# Build parameters
MANIFEST_UUID = 'dee3106d-c2a6-453d-825d-b5632f703b56'
VERSION = 'v1.20'
PLATFORM = 'darwin-arm64'
CHECKSUM = '8e28a1d587c8a21b5d9fe5e540e334a23d39aad870caeb5a3b9371e95b33c472'
FILENAME = 'shuttersense-agent-darwin-arm64'
FILE_SIZE = 73978176


def upgrade() -> None:
    """Insert release manifest and artifact for v1.20 (darwin-arm64)."""
    bind = op.get_bind()
    dialect = bind.dialect.name

    release_manifests = table(
        'release_manifests',
        column('id', sa.Integer),
        column('uuid', sa.LargeBinary if dialect == 'sqlite' else sa.Uuid),
        column('version', sa.String),
        column('platforms_json', sa.Text if dialect == 'sqlite' else JSONB),
        column('checksum', sa.String),
        column('is_active', sa.Boolean),
        column('notes', sa.Text),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime),
    )

    release_artifacts = table(
        'release_artifacts',
        column('id', sa.Integer),
        column('manifest_id', sa.Integer),
        column('platform', sa.String),
        column('filename', sa.String),
        column('checksum', sa.String),
        column('file_size', sa.BigInteger),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime),
    )

    # Convert UUID string to the right format per dialect
    import uuid as uuid_mod
    manifest_uuid = uuid_mod.UUID(MANIFEST_UUID)

    if dialect == 'sqlite':
        uuid_value = manifest_uuid.bytes
        platforms_value = '["' + PLATFORM + '"]'
    else:
        uuid_value = manifest_uuid
        platforms_value = [PLATFORM]

    # Insert the release manifest
    bind.execute(
        release_manifests.insert().values(
            uuid=uuid_value,
            version=VERSION,
            platforms_json=platforms_value,
            checksum=CHECKSUM,
            is_active=True,
            notes='Auto-generated by build script',
            created_at=sa.func.now(),
            updated_at=sa.func.now(),
        )
    )

    # Get the inserted manifest ID
    result = bind.execute(
        sa.select(release_manifests.c.id).where(
            sa.and_(
                release_manifests.c.version == VERSION,
                release_manifests.c.checksum == CHECKSUM,
            )
        )
    )
    manifest_row = result.first()
    if manifest_row is None:
        raise RuntimeError(f"Failed to find inserted manifest for {VERSION}")
    manifest_id = manifest_row[0]

    # Insert the release artifact
    bind.execute(
        release_artifacts.insert().values(
            manifest_id=manifest_id,
            platform=PLATFORM,
            filename=FILENAME,
            checksum='sha256:' + CHECKSUM,
            file_size=FILE_SIZE,
            created_at=sa.func.now(),
            updated_at=sa.func.now(),
        )
    )


def downgrade() -> None:
    """Remove release manifest and artifact for v1.20 (darwin-arm64)."""
    bind = op.get_bind()

    release_artifacts = table(
        'release_artifacts',
        column('manifest_id', sa.Integer),
    )

    release_manifests = table(
        'release_manifests',
        column('id', sa.Integer),
        column('version', sa.String),
        column('checksum', sa.String),
    )

    # Find the manifest
    result = bind.execute(
        sa.select(release_manifests.c.id).where(
            sa.and_(
                release_manifests.c.version == VERSION,
                release_manifests.c.checksum == CHECKSUM,
            )
        )
    )
    manifest_row = result.first()
    if manifest_row is not None:
        manifest_id = manifest_row[0]

        # Delete artifacts first (FK constraint)
        bind.execute(
            release_artifacts.delete().where(
                release_artifacts.c.manifest_id == manifest_id
            )
        )

        # Delete the manifest
        bind.execute(
            release_manifests.delete().where(
                release_manifests.c.id == manifest_id
            )
        )
